- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /api
    state: directory
    mode: '0755'  

- name: Copying frontend image from host to frontend server
  ansible.builtin.copy:
    src: /home/dorde/git/Phase_I_mini_challenge/docker/frontend/frontend.tar
    dest: /api/

- name: Load image from archive
  community.docker.docker_image:
    name: docker-frontend
    tag: latest
    load_path: /api/frontend.tar
    source: load

- name: Run frontend container and publish ports
  community.docker.docker_container:
    name: frontend_app
    image: docker-frontend:latest
    state: started
    restart_policy: always
    published_ports:
      - "8080:80"

- name: Copy healthcheck script to backend server
  ansible.builtin.copy:
    src: /home/dorde/git/Phase_I_mini_challenge/healthcheck.sh
    dest: /usr/local/bin/healthcheck.sh
    owner: root
    group: root
    mode: '0755'

- name: Creates a cronjob with healtcheck script and runs it
  ansible.builtin.cron:
    name: "backend healtcheck"
    job: "/usr/local/bin/healthcheck.sh"
    user: root