- name: General configuring of all servers
  hosts: all
  become: true
  roles:
    - geerlingguy.docker
  tasks:
    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest
        force: true
